maks-1804/maks-prints-repo

README.md
=> added arielles name

server/db/models/category.js
Added a model for categories. Still need to: define associations for the model, instance methods, etc
=> created model for categories

server/db/models/user.js
=> User Model included

server/db/models/cart.js
=> Cart model

server/db/models/index.js, server/db/models/product.js
=> Product branch

server/db/models/cart.js, server/db/models/index.js
=> added some validation and exported the cart model on index.js

server/db/models/index.js, server/db/models/review.js
Added a review model in models folder; added associations for the review model in model/index.
=> Add review model

.eslintrc.json, server/db/models/index.js
we can use Prettier again per no-semicolons group decision
=> Fix for eslintrc

server/api/index.js, server/api/products.js, server/db/models/product.js
refined product model and added framework for product routes
=> Product routes

server/api/users.js
=> user routes included

server/api/products.js
updated query in the get route
=> adjusted product get route

server/api/cart.js, server/api/products.js, server/db/db.js, server/db/models/product.js
added
-- cart routes
-- product routes
-- cart methods
-- product methods
=> Cart routes

server/api/cart.js, server/api/index.js, server/api/products.js
- refactored eager loading
- created cart admin routes
=> Product updates

client/app.js, client/components/navbar.js, client/main.js, package-lock.json, webpack.config.js
made some refactoring of components- mostly just redid the navbar!
=> Navbar component#38

server/db/models/category.js, server/db/models/index.js, server/db/seed.js
This seed file is now able to populate the join table. However (possibly due to explicitly creating with associations?) duplicate Categories are being added to the category table. Working with it for now.
=> seed file refactor- creating instances with associations to populate our join table

server/db/models/product.spec.js
added a simple product spec file which tests the columns of the product model
=> product spec testing columns

server/api/products.js
=> join table querying attempt

server/api/index.js, server/api/reviews.js
=> Reviews routes

server/db/seed.js
Redid the seed file again- separated instance creation from association definition, so we now experience the expected behavior for our join-tables and one-many associations.
=> seed refactored so we no longer get ghost instances

server/api/categories.js, server/api/index.js, server/api/users.js, server/db/models/user.js
=> updated users models/routes and created categories

server/db/seed.js
Some data accidentally got removed from the seed file, everything is back where it should be now
=> restored seed file to working state

client/components/index.js, client/components/nav-category.js, client/components/navbar.js, client/components/product-card.js, client/components/product-list.js, client/main.js, server/api/index.js
Created:
client/components/nav-category.js
client/components/product-card.js
Edited:
modified:   client/components/product-list.js
modified:   client/main.js
modified:   server/api/index.js
=> Products view

client/store/products.js
=> Prod reducer

server/api/carts.js, server/api/products.js, server/db/models/index.js
i moved the admin validation into try / catch blocks for cart and product routes
=> moved user / admin validation into try/catch blocks

server/api/carts.js, server/api/products.js, server/db/models/cart.js, server/db/models/category.js, server/db/models/index.js, server/db/models/user.js
=> changed things to 403

client/components/AccountForm.js, client/components/user/User-EditForm.js, client/store/user.js
made AccountForm
made user-EditForm
edited store/user
=> account form, user-editForm, store/user

client/components/shop/product-list.js, client/store/index.js, client/store/products.js, server/api/users.js
Products now are loaded on componentDidMount !
=> Thunked out all products page

client/components/AccountForm.js, client/components/index.js, client/components/user/User-Dashboard.js, client/components/user/User-EditForm.js, client/components/user/index.js, client/main.js, client/store/user.js, server/api/users.js, server/db/models/user.js, server/db/seed.js
The User Edit Form is pretty fleshed out but has no styling.
The data is preloaded - except for password. I feel like that shouldn't be pre-loaded? Let me know if you want me to add...
We can toggle the view of the password from text to hidden ***.
I also added to the User Model the "Name" input. There are no first and last name separated.
I think we can keep it simple on one form.
=> User edit form

server/api/carts.js
=> Cart notes

public/index.html
=> fixed bootstrap change

client/components/Navbar-Search.js, client/components/navbar.js, client/components/shop/product-list.js, client/store/index.js, client/store/products.js, client/store/search.js, public/index.html, public/style.css, server/api/products.js
Search bar functionality is not complete
- When search submit is clicked, the URL should change to depict the search query
- After we click to another link, the products should equal all products (think lifecycle hooks, or think about making sure that this.props.search is an empty string)
=> search bar

client/store/carts.js, server/api/carts.js
=> Cart reducer

client/components/reviews/Review-Form.js, client/components/reviews/Review-List.js, client/components/reviews/Single-Review.js, client/components/reviews/index.js, client/components/shop/Product-Single.js, package-lock.json, package.json
Fleshed out a little bit more of the single product page- mostly adding a review form. I also added the Moment.js library to our package, so be sure to npm install it. Basically it's a nice library for parsing dates.
I'll tackle getting the review form up and running with thunks etc later on today!
=> Review components

client/components/admin/EditProduct.js, client/components/index.js, client/main.js, package-lock.json
Added component for editing product, as well as admin validation logic and admin routes.
=> All products styling

client/components/reviews/Review-Form.js, client/components/shop/Product-Single.js, public/style.css
component updates for single product page, reviews, and review forms. 
still some styling to do- but now need to concentrate on functionality of:
add to cart
add review
=> updating single product page and reviews and review form

client/components/shop/nav-category.js, client/components/shop/product-list.js, client/store/categories.js, client/store/index.js
We're fetching all categories in our Product List and passing down the categories to NavCat
=> categories store created, navcat is no longer hardcoded

client/components/admin/EditProduct.js, client/main.js
=> deleted the extra isLoggedIn

client/components/reviews/index.js, client/components/user/User-Dashboard.js, server/api/reviews.js
I'm fetching all reviews to the user dashboard since the /auth/me doesn't eager load the reviews to our user page.
=> User Reviews loaded by fetching all reviews

client/components/admin/Admin-Dashboard.js, client/components/admin/index.js, client/components/index.js, client/components/navbar.js, client/components/shop/product-card.js, client/components/user/User-Dashboard.js, client/main.js
Admin Dashboard Skeleton
- Product Management includes button to edit and delete products
=> Admin dashboard

client/components/auth-form.js, client/components/cart/Open-Cart.js, client/components/shop/product-list.js, client/store/carts.js, server/api/carts.js
Upon redirect to /shop after logging in or signing up, the users open cart is found or retrieved.
=> added retrieve open cart functionality on redirect of login/sign up

client/store/carts.js
fixed a bug where the cart did not properly update the number of items in the cart if you're adding the first item to the cart
=> fixed bug for adding to a cart for the first time

client/components/admin/AddProduct.js, server/api/products.js
Can now add categories to the new products
=> add category to new products

client/components/cart/Cart-History.js, client/components/cart/Open-Cart.js, client/components/shop/Product-Single.js, client/components/shop/product-list.js, client/store/cart.js, client/store/cartList.js, client/store/carts.js, client/store/index.js
since cart reducer is an object
&&
since getting carts will be an array...
I reorganized the file structure in the store a bit to reflect the two different reducers. Now we have cart.js (for single cart) and cartList.js (for cart lists)
=> Order history

client/components/cart/Cart-History.js, client/components/cart/Cart-HistoryCard.js, client/components/cart/Cart-ProductCard.js, client/components/cart/Open-Cart.js, client/store/cart.js, client/store/cartList.js, client/store/index.js, public/index.html, public/style.css, server/db/models/cart.js, server/db/seed.js
Added more style to the cart page.
You can now see your order history if you're logged in.
some changes to the seed file (additions)
added more status options to cart model
=> 11 file changes

client/components/admin/AddProduct.js, client/components/admin/Admin-Dashboard.js, client/components/admin/UserCard.js, client/components/auth-form.js, client/components/navbar.js, client/components/reviews/Review-List.js, client/components/reviews/Single-Review.js, client/components/shop/Product-Single.js, client/components/shop/product-card.js, client/components/user/User-Dashboard.js, client/components/user/User-EditForm.js, public/index.html, public/style.css
Added Materialize CSS Styling to our forms and dashboards.
=> Materialize css

client/components/admin/EditProduct.js
Edit form now prepopulates with product data
=> working edit product form for admin

client/components/shop/Product-Single.js
form was defaulting to zero- now defaults to one! fixed!
=> bug fix for adding first product to a cart 

public/index.html
=> removing styling temp

client/components/cart/Cart-ProductCard.js, client/components/shop/Product-Single.js, client/components/user/User-EditForm.js, public/index.html
=> dropdown with materialize

server/db/models/cart.js
fixed type on a model that affected the deployment
=> fixed typo

client/components/navbar.js
=> fixed shop link for navbar

client/components/cart/Cart-HistoryCard.js, client/components/cart/CartHistory.js, client/components/cart/index.js, client/components/reviews/SingleReview.js, client/components/user/User-Dashboard.js, public/style.css
User Dashboard has Order History
Still needs to be styled
SingleReview does not render with the image.
=> moved order history to userDash

client/components/cart/Cart-ProductCard.js, client/components/cart/OpenCart.js, public/style.css
Removed order history form open cart page since it is now on the user account page. styled it a bit
=> open cart styles

client/components/admin/AdminDashboard.js, client/components/admin/UserCard.js, client/components/cart/Cart-HistoryCard.js, client/components/cart/CartHistory.js, client/components/cart/OpenCart.js, client/store/cartList.js, server/api/carts.js
Admin Dashboard has all categories
=> Admin edit user

client/components/cart/Cart-HistoryCard.js, client/components/cart/CartHistory.js
fixed the styling (spacing) on past orders
=> past order styling

server/api/checkout.js
hopefully this change will allow us to deploy on heroku
=> stripe config
